### ISSUE TITLE
Total.js on Cpanel server

### ISSUE THREAD

**Issue by hostcubit** [totaljs/cms#10]
Hi ... First of all I want to congratulate the developers of this script for the great work contributed

I installed the script on a Cpanel server, I activate the proxy modules in apache ( WHM EA4 ) and in the installation of the cms app configure the .htaccess

Everything works perfectly, except the **home page / returns 404**   **What can this be due to?**

Thanks in advance

# BEGIN SSL
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTPS} !=on [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
</IfModule>
# END SSL

# BEGIN Total.js
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^(.*)$ http://%{HTTP_HOST}:8000/$1 [P,L]
</IfModule>

**Comment by petersirka** [comment]
Hi @hostcubit - __thank you__, do other pages work? Does the homepage work on your localhost? I don't have any experience with Cpanel. 

BTW: Is `404` from Total.js or from Apache? If yes are you sure you have registered `/` homepage page in CMS? If __yes__ then a problem can be in `URL`, just try to log requests in Total.js and try to capture URL address from your proxy:

```javascript
ON('request', function(req) {
    console.log(req.url); // it must be "/" for homepage
});
```

**Comment by hostcubit** [comment]
yes on localhost works perfectly 

https://hostqubit.com/    --- 404

https://hostqubit.com/blog/   --- ok

**Comment by petersirka** [comment]
Try capture URL as I wrote before. I'm on a business trip, but I'll be online today later. Let me know to result.

**Comment by hostcubit** [comment]
Ok thank you 

In console log this:

/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico
/index.js
/favicon.ico

**Comment by petersirka** [comment]
I think there is a problem in a reverse proxy... This is my log result:

```html
/
/widgets.css?ts=hygfx
/default/css/default.css
/default/js/default.js
/default/img/logo.png
/$visitors/
```
