### ISSUE TITLE
does totaljs cms support nginx deploy into subdirectory?

### ISSUE THREAD

**Issue by tianyingchun** [totaljs/cms#21]
dear team,

how totaljs-cms can support deploy it into subfolder using nginx

e.g  my domain is www.example.com
i want to access this cms via http://www.example.com/fex/porta/

how to do it ?

**Comment by petersirka** [comment]
Hi @tianyingchun,
not possible yet. CMS is optimized for the root path domain only, it can't be part of subfolder.

**Comment by tianyingchun** [comment]
i think it's very useful feature for most users. do  you have plan to support this features?

**Comment by petersirka** [comment]
We will see, but not in the short time.

**Comment by tianyingchun** [comment]
:)

**Comment by petersirka** [comment]
I don't added a support for relative paths, it's a bit complicated and useless for most of cases. Currently I'm closing this issue.
