### ISSUE TITLE
can't create a new user

### ISSUE THREAD

**Issue by dzxt** [totaljs/cms#25]
Hi there
I installed CMS 13.0.0 on the local mac os 10.14.6 Mojave computer. + Node js v13.13.0
1) I create a new user with super administrator rights
2) cms will be refused due to incorrect authentication data when attempting to login
3) when I go back under the default administrator, I see that the new user has not been saved and has disappeared from the list of users on the settings page
https://drive.google.com/file/d/15tVR5HFJ9Vhr5EY0ljn-EhFmcs6XUBFz/view?usp=sharing
Thanks!

**Comment by petersirka** [comment]
Have you applied settings via right top button `APPLY SETTINGS`?

**Comment by dzxt** [comment]
Thank you for the quick response, I did not pay attention to this button, however after adding a user it remains unavailable for clicking. https://prnt.sc/se29pb

**Comment by petersirka** [comment]
Yes because there is missing some required settings. Check required fields:

![image](https://user-images.githubusercontent.com/2414252/81494268-e1942e80-92a7-11ea-99eb-85d1ccfa7b50.png)

**Comment by dzxt** [comment]
That's it!  I understand the principle, so I confirm all the settings on the page at once
Thank you
