### ISSUE TITLE
Instruction in readme.md is wrong

### ISSUE THREAD

**Issue by xstable** [totaljs/cms#3]
You write: 

> innstall $ npm install total.js
> open cms directory $ cd cms
> run it node debug.js

But there is no /cms. So erase the second line, and all will be fine :)

**Comment by molda** [comment]
Hi @xstable it assumes you've named the directory **cms** or used git to download it which would create the dir for you.
But it should probably be more like this to make it clear:

```bash
$ git clone https://github.com/totaljs/cms.git
$ cd cms
$ npm install total.js
$ node debug.js
```

I'll update the readme.

Thanks.
