### ISSUE TITLE
[Security] Stored XSS

### ISSUE THREAD

**Issue by edoardottt** [totaljs/cms#39]
Tested version: [8c2c8909](https://github.com/totaljs/cms/commit/8c2c8909bf23a9daece47bd4fd9537ad52c03b0e) (latest)

Steps to reproduce the vulnerability:
- Login in the application.
- Set `"</script><script>alert(document.domain)</script>` as CDN (for jComponent Library) in settings.
- Fill other required fields with random values and save.
- Then just visit the admin dashboard and the alert will fire.

Each time a target will visit the dashboard the payload will fire, even if the target is not logged in! Since the wesbite redirects to /admin/ presenting the login form, but the payload is reflected also there.

In order to test this, just click logout and reload the page.

![Screenshot from 2022-09-19 19-30-33](https://user-images.githubusercontent.com/35783570/191078285-d6aeb05b-47af-474d-b885-5c85f06c17ba.png)

![Screenshot from 2022-09-19 17-48-46](https://user-images.githubusercontent.com/35783570/191059066-8474de05-389c-43ee-aa1a-7957a6f5725c.png)

**Comment by petersirka** [comment]
Hi @edoardottt,
This is not a security issue. It's an administration area, and you must have enabled `sa` privileges for editing those settings. If you look into the widgets/pages/layouts you can easily inject scripts (and not only for client-side...).
