### ISSUE TITLE
There is an unauthorized vulnerability in totaljscms

### ISSUE THREAD

**Issue by ainiy-top** [totaljs/cms#44]
Upload the 1. txt file and click download
 
![图片1](https://github.com/totaljs/cms/assets/81848507/6ff6c87e-f4d5-46ed-aaf3-7f192045a04f)

Copy the download link for 1. txt
 
![图片2](https://github.com/totaljs/cms/assets/81848507/9f348040-8982-4411-be82-13d56d90af98)

Replace the Google browser with an administrator account that has not been logged in for access, and successfully download the file without authorization.
 
![图片3](https://github.com/totaljs/cms/assets/81848507/cff73db4-4874-40ae-ab18-0e25e42a475c)

**Comment by petersirka** [comment]
Those files are public. What should it mean to make non-public files in CMS?
